version: '3.8'

services:
    mysql:
      image: mysql:latest
      container_name: mysql
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ports:
        - "3306:3306"
      volumes:
        - mysql_data:/var/lib/mysql

    controller:
      image: ngrinder/controller:3.5.5-p1
      restart: always
      ports:
        - "9000:80"
        - "16001:16001"
        - "12000-12009:12000-12009"
      volumes:
        - ./ngrinder-controller:/opt/ngrinder-controller
    agent:
      image: ngrinder/agent:3.5.5-p1
      restart: always
      links:
        - controller


volumes:
    mysql_data:

