version: '3.8'

services:
  springboot:
    container_name: marketplace
    image: ${DOCKER_USER}/${DOCKER_REPO}:marketplace-server  # Docker Hub에서 가져올 이미지
    volumes:
      - /home/serverking/marketplace:/app/image
    ports:
      - "8088:8080"
    environment:
      TZ: "Asia/Seoul"
